import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e2e7ff",
        "on-secondary": "#ffffff",
        "surface-tint": "#0e6b52",
        "background": "#faf8ff",
        "on-surface-variant": "#3f4944",
        "tertiary-fixed-dim": "#ffb4a9",
        "primary-fixed": "#a1f3d3",
        "on-background": "#141b2e",
        "on-primary-fixed": "#002117",
        "primary-container": "#0e6b52",
        "tertiary": "#74322b",
        "surface-variant": "#dbe2fc",
        "on-primary": "#ffffff",
        "secondary-fixed": "#ffdea6",
        "primary-fixed-dim": "#86d6b7",
        "on-tertiary-container": "#ffccc5",
        "on-error": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "on-secondary-fixed": "#271900",
        "on-secondary-fixed-variant": "#5d4200",
        "on-tertiary": "#ffffff",
        "secondary": "#7b5800",
        "inverse-on-surface": "#eef0ff",
        "surface": "#faf8ff",
        "surface-bright": "#faf8ff",
        "error": "#ba1a1a",
        "outline-variant": "#bec9c2",
        "on-error-container": "#93000a",
        "inverse-surface": "#293044",
        "inverse-primary": "#86d6b7",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#97e8c9",
        "secondary-container": "#fdc34d",
        "on-tertiary-fixed": "#3b0805",
        "primary": "#00513d",
        "outline": "#6f7a74",
        "surface-container-highest": "#dbe2fc",
        "secondary-fixed-dim": "#f7bd48",
        "tertiary-fixed": "#ffdad5",
        "surface-dim": "#d3d9f3",
        "on-surface": "#141b2e",
        "on-secondary-container": "#715000",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#00513d",
        "on-tertiary-fixed-variant": "#74332b",
        "surface-container": "#eaedff",
        "tertiary-container": "#914940",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        base: "8px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
      },
      fontFamily: {
        "body-lg": ["var(--font-inter)"],
        "label-md": ["var(--font-inter)"],
        "body-md": ["var(--font-inter)"],
        "display-lg": ["var(--font-source-serif)"],
        "headline-lg-mobile": ["var(--font-source-serif)"],
        "document-title": ["var(--font-source-serif)"],
        "headline-lg": ["var(--font-source-serif)"],
        "label-sm": ["var(--font-inter)"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", fontWeight: "600" },
        ],
        "document-title": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};
export default config;
