"""add_parties_and_facts_fields

Revision ID: 2da990d4a69a
Revises: 201435cbfa69
Create Date: 2026-07-07 09:30:00.300351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2da990d4a69a'
down_revision = '201435cbfa69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_scrape_status'), table_name='scrape_log')
    op.drop_table('scrape_log')
    op.add_column('drafts', sa.Column('advocate_name', sa.String(), nullable=True))
    op.add_column('drafts', sa.Column('advocate_enrollment_no', sa.String(), nullable=True))
    op.add_column('drafts', sa.Column('petitioners', sa.JSON(), nullable=True))
    op.add_column('drafts', sa.Column('respondents', sa.JSON(), nullable=True))
    op.add_column('drafts', sa.Column('impugned_order_date', sa.DateTime(), nullable=True))
    op.add_column('drafts', sa.Column('jurisdiction_basis', sa.String(), nullable=True))
    op.add_column('drafts', sa.Column('interim_relief_sought', sa.String(), nullable=True))
    op.alter_column('drafts', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('drafts', 'case_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('drafts', 'court',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('drafts', 'form_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('drafts', 'draft_html',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('drafts', 'draft_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('drafts', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'::text"))
    op.drop_index(op.f('idx_drafts_status'), table_name='drafts')
    op.drop_index(op.f('idx_drafts_user'), table_name='drafts')
    op.alter_column('judgment_chunks', 'chunk_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('judgments', 'case_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('judgments', 'case_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('judgments', 'judgment_date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('judgments', 'bench',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('judgments', 'petitioner',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('judgments', 'respondent',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('judgments', 'acts_cited',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('judgments', 'cases_cited',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('judgments', 'full_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('judgments', 'content_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('judgments', 'pdf_s3_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('judgments', 'summary',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('judgments', 'holding',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_case_number'), table_name='judgments')
    op.drop_index(op.f('idx_case_type'), table_name='judgments')
    op.drop_index(op.f('idx_content_hash'), table_name='judgments')
    op.drop_index(op.f('idx_year'), table_name='judgments')
    op.drop_column('judgments', 'applicability')
    op.drop_column('judgments', 'scraped_at')
    op.drop_column('judgments', 'source_url')
    op.drop_column('judgments', 'result')
    op.drop_column('judgments', 'title')
    op.drop_column('judgments', 'quality_score')
    op.drop_column('judgments', 'tags')
    op.alter_column('legal_code_sections', 'section_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('legal_code_sections', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('legal_code_sections', 'section_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('legal_code_sections', 'corresponds_to',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_lcs_embedding'), table_name='legal_code_sections', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '50'}, postgresql_using='ivfflat')
    op.drop_index(op.f('idx_lcs_section_num'), table_name='legal_code_sections')
    op.alter_column('legal_codes', 'code_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('legal_codes', 'short_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('legal_codes', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'active'::text"))
    op.alter_column('payments', 'razorpay_order_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('payments', 'razorpay_payment_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('payments', 'currency',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'INR'::text"))
    op.alter_column('payments', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('search_logs', 'query',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('search_logs', 'search_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('subscriptions', 'razorpay_sub_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('subscriptions', 'plan_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('uploaded_docs', 'original_filename',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('uploaded_docs', 'r2_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('uploaded_docs', 'doc_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('uploaded_docs', 'ocr_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('uploaded_docs', 'verify_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('uploaded_docs', 'verify_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'clerk_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'plan',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'free'::text"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'plan',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'free'::text"))
    op.alter_column('users', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'clerk_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('uploaded_docs', 'verify_reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('uploaded_docs', 'verify_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('uploaded_docs', 'ocr_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('uploaded_docs', 'doc_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('uploaded_docs', 'r2_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('uploaded_docs', 'original_filename',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('subscriptions', 'plan_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('subscriptions', 'razorpay_sub_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('search_logs', 'search_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('search_logs', 'query',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('payments', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('payments', 'currency',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'INR'::text"))
    op.alter_column('payments', 'razorpay_payment_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('payments', 'razorpay_order_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('legal_codes', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'active'::text"))
    op.alter_column('legal_codes', 'short_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('legal_codes', 'code_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_lcs_section_num'), 'legal_code_sections', ['section_number'], unique=False)
    op.create_index(op.f('idx_lcs_embedding'), 'legal_code_sections', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '50'}, postgresql_using='ivfflat')
    op.alter_column('legal_code_sections', 'corresponds_to',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('legal_code_sections', 'section_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('legal_code_sections', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('legal_code_sections', 'section_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('judgments', sa.Column('tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('judgments', sa.Column('quality_score', sa.REAL(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('judgments', sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('judgments', sa.Column('result', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('judgments', sa.Column('source_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('judgments', sa.Column('scraped_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('judgments', sa.Column('applicability', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_year'), 'judgments', ['year'], unique=False)
    op.create_index(op.f('idx_content_hash'), 'judgments', ['content_hash'], unique=False)
    op.create_index(op.f('idx_case_type'), 'judgments', ['case_type'], unique=False)
    op.create_index(op.f('idx_case_number'), 'judgments', ['case_number'], unique=False)
    op.alter_column('judgments', 'holding',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('judgments', 'summary',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('judgments', 'pdf_s3_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('judgments', 'content_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('judgments', 'full_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('judgments', 'cases_cited',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('judgments', 'acts_cited',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('judgments', 'respondent',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('judgments', 'petitioner',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('judgments', 'bench',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('judgments', 'judgment_date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('judgments', 'case_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('judgments', 'case_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('judgment_chunks', 'chunk_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_drafts_user'), 'drafts', ['user_id'], unique=False)
    op.create_index(op.f('idx_drafts_status'), 'drafts', ['status'], unique=False)
    op.alter_column('drafts', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'::text"))
    op.alter_column('drafts', 'draft_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('drafts', 'draft_html',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('drafts', 'form_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('drafts', 'court',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('drafts', 'case_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('drafts', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('drafts', 'interim_relief_sought')
    op.drop_column('drafts', 'jurisdiction_basis')
    op.drop_column('drafts', 'impugned_order_date')
    op.drop_column('drafts', 'respondents')
    op.drop_column('drafts', 'petitioners')
    op.drop_column('drafts', 'advocate_enrollment_no')
    op.drop_column('drafts', 'advocate_name')
    op.create_table('scrape_log',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_msg', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('scrape_log_pkey')),
    sa.UniqueConstraint('key', name=op.f('scrape_log_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_scrape_status'), 'scrape_log', ['status'], unique=False)
    # ### end Alembic commands ###
