"""Add dates_and_events to Draft

Revision ID: 3be6a5fbfa53
Revises: 7bd073c8761a
Create Date: 2026-07-11 11:47:19.290265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be6a5fbfa53'
down_revision = '7bd073c8761a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drafts', sa.Column('dates_and_events', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drafts', 'dates_and_events')
    # ### end Alembic commands ###
