"""add_legal_code_sections_bm25

Revision ID: 5180f064fc79
Revises: 2da990d4a69a
Create Date: 2026-07-07 10:36:30.294248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5180f064fc79'
down_revision = '2da990d4a69a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legal_code_sections', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    # ### end Alembic commands ###
    
    # Create weighted BM25 trigger: title→A (highest), section_text→B
    op.execute("""
        CREATE OR REPLACE FUNCTION legal_code_sections_search_trigger() RETURNS trigger AS $$
        BEGIN
          NEW.search_vector :=
            setweight(to_tsvector('english', coalesce(NEW.title, '')), 'A') ||
            setweight(to_tsvector('english', coalesce(NEW.section_text, '')), 'B');
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER legal_code_sections_search_update
          BEFORE INSERT OR UPDATE ON legal_code_sections
          FOR EACH ROW EXECUTE FUNCTION legal_code_sections_search_trigger();
    """)
    # GIN index for fast full-text queries
    op.execute("CREATE INDEX idx_lcs_search ON legal_code_sections USING GIN(search_vector);")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legal_code_sections', 'search_vector')
    # ### end Alembic commands ###
