"""add_gapfill_tables

Revision ID: 717d20c72fc7
Revises: cb4aa2e4800c
Create Date: 2026-07-13 14:37:05.901779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '717d20c72fc7'
down_revision = 'cb4aa2e4800c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_gap_analytics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_type_key', sa.String(), nullable=False),
    sa.Column('suggested_question', sa.String(), nullable=False),
    sa.Column('why_relevant', sa.String(), nullable=True),
    sa.Column('was_answered', sa.Boolean(), nullable=True),
    sa.Column('was_skipped', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_gap_analytics_document_type_key'), 'context_gap_analytics', ['document_type_key'], unique=False)
    op.create_table('document_field_requirements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_type_key', sa.String(), nullable=False),
    sa.Column('field_key', sa.String(), nullable=False),
    sa.Column('field_label', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('min_length', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_type_key', 'field_key', name='uq_doc_field_req')
    )

    op.add_column('drafts', sa.Column('chatbot_gap_fill_log', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))
    op.add_column('drafts', sa.Column('additional_context', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drafts', 'additional_context')
    op.drop_column('drafts', 'chatbot_gap_fill_log')

    op.drop_table('document_field_requirements')
    op.drop_index(op.f('ix_context_gap_analytics_document_type_key'), table_name='context_gap_analytics')
    op.drop_table('context_gap_analytics')
    # ### end Alembic commands ###
