"""Add hierarchy models

Revision ID: 7bd073c8761a
Revises: eaf356330fcb
Create Date: 2026-07-08 20:51:31.353098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bd073c8761a'
down_revision = 'eaf356330fcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hierarchy_categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('court_level', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hierarchy_case_types',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('defective', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['hierarchy_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hierarchy_document_requirements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('case_type_id', sa.BigInteger(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('requirement_type', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_type_id'], ['hierarchy_case_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hierarchy_sub_categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('case_type_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_type_id'], ['hierarchy_case_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hierarchy_sub_categories')
    op.drop_table('hierarchy_document_requirements')
    op.drop_table('hierarchy_case_types')
    op.drop_table('hierarchy_categories')
    # ### end Alembic commands ###
