"""Add mandatory_paragraphs to Draft

Revision ID: 99481db9134d
Revises: 3be6a5fbfa53
Create Date: 2026-07-11 12:00:58.912635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99481db9134d'
down_revision = '3be6a5fbfa53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drafts', sa.Column('mandatory_paragraphs', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drafts', 'mandatory_paragraphs')
    # ### end Alembic commands ###
