"""add upload_session_id to uploaded_docs

Groups the documents uploaded during a single drafting-wizard session, which
begins before the `drafts` row exists. Used by POST /api/v1/uploads/extract-fields
to gather the OCR text for auto-populating Step 5, and by /gapfill/start to
back-link those rows to the draft once it is created.

Hand-written, not autogenerated — the models drift from the live schema and
autogenerate produces destructive collateral (see 2da990d4a69a).

Revision ID: a1f7c3e9b204
Revises: 0be004d4868a
Create Date: 2026-07-29
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a1f7c3e9b204'
down_revision: Union[str, None] = '0be004d4868a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'uploaded_docs',
        sa.Column('upload_session_id', sa.String(length=64), nullable=True),
    )
    # Partial index: the column is NULL for every pre-existing row, so only the
    # small "in-flight wizard session" working set is indexed.
    op.create_index(
        'idx_uploaded_docs_session',
        'uploaded_docs',
        ['upload_session_id'],
        unique=False,
        postgresql_where=sa.text('upload_session_id IS NOT NULL'),
    )


def downgrade() -> None:
    op.drop_index('idx_uploaded_docs_session', table_name='uploaded_docs')
    op.drop_column('uploaded_docs', 'upload_session_id')
