"""add language and translation columns to uploaded_docs

Hindi uploads are translated to English at OCR time (app/core/language.py) so
that `ocr_text` stays the English-facing column and every consumer of it —
verification, field extraction, the drafting prompt and the English-indexed
citation retrieval — keeps working unchanged.

  ocr_lang            'en' | 'hi' | 'mixed' | 'unknown'
  ocr_text_original   the pre-translation text, kept for audit. NULL unless a
                      translation actually happened, so English uploads (the
                      common case) cost no extra storage.
  translation_status  'not_needed' | 'translated' | 'partial' | 'failed' |
                      'disabled'

All nullable: pre-existing rows read as NULL, meaning "never went through the
layer", which is distinguishable from 'not_needed'.

No index — these are read alongside the row, never filtered on.

Hand-written, not autogenerated — the models drift from the live schema and
autogenerate produces destructive collateral (see 2da990d4a69a).

Revision ID: b2d4e6f8a103
Revises: a1f7c3e9b204
Create Date: 2026-08-03
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b2d4e6f8a103'
down_revision: Union[str, None] = 'a1f7c3e9b204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('uploaded_docs', sa.Column('ocr_lang', sa.String(length=16), nullable=True))
    op.add_column('uploaded_docs', sa.Column('ocr_text_original', sa.Text(), nullable=True))
    op.add_column('uploaded_docs', sa.Column('translation_status', sa.String(length=16), nullable=True))


def downgrade() -> None:
    op.drop_column('uploaded_docs', 'translation_status')
    op.drop_column('uploaded_docs', 'ocr_text_original')
    op.drop_column('uploaded_docs', 'ocr_lang')
