"""add trigram indexes on judgment party columns

The case-name OR-fallback in core/rag.py finds a judgment by its cause title, so
it filters `petitioner`/`respondent` with ILIKE '%name%'. A leading wildcard
cannot use a btree index, so every fallback was a sequential scan of all 39,506
judgments — ~12,600 page reads. On Neon's cold page cache that ran 9-14 seconds
and blew RAG_OR_FALLBACK_TIMEOUT_MS (4s), so the fallback died with
QueryCanceledError for exactly the queries it exists to serve.

Measured on the live corpus for the query `Kumar | Verma`:

    before   Seq Scan            cost 14,003    cold 9.53s   warm 1.80s
    after    BitmapOr on trgm    cost  7,431    cold 3.74s   warm 0.08s

pg_trgm is required for gin_trgm_ops. Both statements are IF NOT EXISTS: the
indexes were created directly on the live database when the regression was
diagnosed, so this migration is a no-op there and exists to make the schema
reproducible in a fresh environment.

Build cost is trivial (0.6s each on 39.5k rows), so a plain CREATE INDEX is used
rather than CONCURRENTLY — which cannot run inside Alembic's transaction anyway.
`judgments` is a read-mostly corpus ingested offline, so the brief write lock is
not contended.

Hand-written, not autogenerated — the models drift from the live schema and
autogenerate produces destructive collateral (see 2da990d4a69a).

Revision ID: c3f5a7b9d216
Revises: b2d4e6f8a103
Create Date: 2026-08-03
"""
from typing import Sequence, Union

from alembic import op


revision: str = 'c3f5a7b9d216'
down_revision: Union[str, None] = 'b2d4e6f8a103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_judgments_petitioner_trgm "
        "ON judgments USING gin (petitioner gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_judgments_respondent_trgm "
        "ON judgments USING gin (respondent gin_trgm_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS idx_judgments_respondent_trgm")
    op.execute("DROP INDEX IF EXISTS idx_judgments_petitioner_trgm")
    # pg_trgm is left installed: other objects may depend on it, and dropping an
    # extension is not a safe inverse of CREATE EXTENSION IF NOT EXISTS.
