"""Add section_format_overrides to Draft and User

Revision ID: cb4aa2e4800c
Revises: 99481db9134d
Create Date: 2026-07-11 15:44:04.503682

"""
from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb4aa2e4800c'
down_revision = '99481db9134d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('court_identities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('court_level', sa.String(), nullable=False),
    sa.Column('court_name', sa.String(), nullable=False),
    sa.Column('short_code', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('has_benches', sa.Boolean(), nullable=True),
    sa.Column('rule_book_title', sa.String(), nullable=True),
    sa.Column('rule_book_source_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('court_name'),
    sa.UniqueConstraint('short_code')
    )
    op.create_table('document_structure_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('applies_to', sa.String(), nullable=False),
    sa.Column('rule_key', sa.String(), nullable=False),
    sa.Column('rule_description', sa.Text(), nullable=False),
    sa.Column('is_heading', sa.Boolean(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('applies_to', 'rule_key')
    )
    op.create_table('mandatory_paragraphs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('court_level', sa.String(), nullable=False),
    sa.Column('bench_name', sa.String(), nullable=True),
    sa.Column('document_type_key', sa.String(), nullable=False),
    sa.Column('para_key', sa.String(), nullable=False),
    sa.Column('para_label', sa.String(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('placement', sa.String(), nullable=True),
    sa.Column('is_heading', sa.Boolean(), nullable=True),
    sa.Column('is_conditional', sa.Boolean(), nullable=True),
    sa.Column('condition_note', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_citation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('court_level', 'bench_name', 'document_type_key', 'para_key')
    )
    op.create_table('court_benches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('court_identity_id', sa.BigInteger(), nullable=False),
    sa.Column('bench_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['court_identity_id'], ['court_identities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('court_identity_id', 'bench_name')
    )
    op.create_table('court_formatting_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('court_identity_id', sa.BigInteger(), nullable=True),
    sa.Column('court_level', sa.String(), nullable=True),
    sa.Column('font_family', sa.String(), nullable=True),
    sa.Column('body_font_size', sa.String(), nullable=True),
    sa.Column('line_spacing', sa.String(), nullable=True),
    sa.Column('margin_left_inches', sa.Numeric(), nullable=True),
    sa.Column('margin_right_inches', sa.Numeric(), nullable=True),
    sa.Column('margin_top_inches', sa.Numeric(), nullable=True),
    sa.Column('margin_bottom_inches', sa.Numeric(), nullable=True),
    sa.Column('margin_style', sa.String(), nullable=True),
    sa.Column('paper_finish', sa.String(), nullable=True),
    sa.Column('court_language', sa.String(), nullable=True),
    sa.Column('requires_para_numbering', sa.Boolean(), nullable=True),
    sa.Column('paper_size', sa.String(), nullable=True),
    sa.Column('is_sourced_from_rulebook', sa.Boolean(), nullable=True),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['court_identity_id'], ['court_identities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('court_rule_document_mapping',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('court_identity_id', sa.BigInteger(), nullable=False),
    sa.Column('document_type_key', sa.String(), nullable=False),
    sa.Column('chapter_number', sa.String(), nullable=False),
    sa.Column('relevance_note', sa.Text(), nullable=True),
    sa.Column('is_mandatory_source', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['court_identity_id'], ['court_identities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('court_identity_id', 'document_type_key', 'chapter_number')
    )
    op.create_table('court_rule_sections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('court_identity_id', sa.BigInteger(), nullable=False),
    sa.Column('part_name', sa.String(), nullable=True),
    sa.Column('chapter_number', sa.String(), nullable=False),
    sa.Column('chapter_title', sa.String(), nullable=True),
    sa.Column('rule_number', sa.String(), nullable=True),
    sa.Column('rule_subsection', sa.String(), nullable=True),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['court_identity_id'], ['court_identities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('court_identity_id', 'chapter_number', 'rule_number', 'rule_subsection')
    )
    op.add_column('drafts', sa.Column('section_format_overrides', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('default_section_format_overrides', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_section_format_overrides')
    op.drop_column('drafts', 'section_format_overrides')
    op.drop_table('court_rule_sections')
    op.drop_table('court_rule_document_mapping')
    op.drop_table('court_formatting_rules')
    op.drop_table('court_benches')
    op.drop_table('mandatory_paragraphs')
    op.drop_table('document_structure_rules')
    op.drop_table('court_identities')
    # ### end Alembic commands ###
