"""add court models

Revision ID: eaf356330fcb
Revises: 5180f064fc79
Create Date: 2026-07-08 19:00:53.658664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf356330fcb'
down_revision = '5180f064fc79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('high_courts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('territory', sa.JSON(), nullable=True),
    sa.Column('principal_seat_city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_high_courts_id'), 'high_courts', ['id'], unique=False)
    op.create_index(op.f('ix_high_courts_name'), 'high_courts', ['name'], unique=True)
    op.create_table('high_court_benches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('high_court_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('bench_type', sa.String(), nullable=True),
    sa.Column('jurisdiction_districts', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['high_court_id'], ['high_courts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_high_court_benches_id'), 'high_court_benches', ['id'], unique=False)
    op.drop_index(op.f('idx_lcs_search'), table_name='legal_code_sections', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_lcs_search'), 'legal_code_sections', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_high_court_benches_id'), table_name='high_court_benches')
    op.drop_table('high_court_benches')
    op.drop_index(op.f('ix_high_courts_name'), table_name='high_courts')
    op.drop_index(op.f('ix_high_courts_id'), table_name='high_courts')
    op.drop_table('high_courts')
    # ### end Alembic commands ###
