export const districtCourtsData: Record<string, string[]> = {
  "Andaman and Nicobar Islands": [
    "District and Sessions Court, South Andaman"
  ],
  "Andhra Pradesh": [
    "Ananthapuramu District Court",
    "Chittoor District Court",
    "East Godavari District Court",
    "Guntur District Court",
    "Kadapa District Court",
    "Krishna District Court",
    "Kurnool District Court",
    "Prakasam District Court",
    "SPSR Nellore District Court",
    "Srikakulam District Court",
    "Visakhapatnam District Court",
    "Vizianagaram District Court",
    "West Godavari District Court"
  ],
  "Arunachal Pradesh": [
    "Chief Judicial Magistrate-cum-Civil Court, Lower Dibang Valley District",
    "District Court Upper Subansiri",
    "District Court, Changlang",
    "District Court, Ziro",
    "District Judiciary, Kra Daadi District",
    "District Judiciary, Lepa Rada",
    "District Judiciary, Lohit District",
    "District Judiciary, Tirap",
    "District Judiciary, West Kameng",
    "District Judiciary, West Siang",
    "District and Sessions Court, Pasighat",
    "District and Sessions Court, Yupia, Papum Pare District",
    "East Kameng District Judiciary",
    "JMFC cum Civil Judge (Jr. Div.) Yingkiong",
    "Judicial Magistrate First Class cum Civil Judge Court, Longding District",
    "Judicial Magistrate First Class-cum-Civil Court (Junior Division), Tawang District",
    "Judicial Magistrate First Class-cum-Civil Court, Anjaw District",
    "Judicial Magistrate First Class-cum-Civil Court, Dibang Valley District",
    "Judicial Magistrate First Class-cum-Civil Court, Namsai District",
    "Judicial Magistrate First Class-cum-Civil Judge (Jr. Div.), Siang District",
    "Judicial Magistrate First Class, Kurung Kumey District"
  ],
  "Assam": [
    "Bajali District Judiciary",
    "Baksa District Judiciary",
    "Barpeta District Judiciary",
    "Biswanath District Judiciary",
    "Bongaigaon District Judiciary",
    "Cachar District Judiciary",
    "Chirang District Judiciary",
    "Darrang District Judiciary",
    "Dhemaji District Judiciary",
    "Dhubri District Judiciary",
    "Dibrugarh District Judiciary",
    "Dima Hasao District Judiciary",
    "Charaideo District Court",
    "Hojai District Judiciary",
    "Goalpara District Judiciary",
    "Golaghat District Judiciary",
    "Hailakandi District Judiciary",
    "Jorhat District Judiciary",
    "Kamrup Metro District Judiciary",
    "Kamrup, Amingaon District Judiciary",
    "Karbi Anglong District Judiciary",
    "Karimganj District Judiciary",
    "Kokrajhar District Judiciary",
    "Lakhimpur District Judiciary",
    "Majuli District Judiciary",
    "Morigaon District Judiciary",
    "Nagaon District Judiciary",
    "Nalbari District Judiciary",
    "Sivasagar District Judiciary",
    "Sonitpur District Judiciary",
    "South Salmara-Mankachar District Judiciary",
    "Tinsukia District Judiciary",
    "Udalguri District Court",
    "West Karbi Anglong District Judiciary"
  ],
  "Bihar": [
    "Banka District Court",
    "Civil Court Rohtas (Sasaram)",
    "Civil Court, Kaimur(Bhabhua)",
    "District Court Araria",
    "District Court Aurangabad",
    "District Court Begusarai",
    "District Court Bhagalpur",
    "District Court Bhojpur",
    "District Court Buxar",
    "District Court Darbhanga",
    "District Court Gaya",
    "District Court Gopalganj",
    "District Court Jamui",
    "District Court Jehanabad",
    "District Court Katihar",
    "District Court Lakhisarai",
    "District Court Madhepura",
    "District Court Munger",
    "District Court Muzaffarpur",
    "District Court Nalanda",
    "District Court Saharsa",
    "District Court Samastipur",
    "District Court Sheikhpura",
    "District Court Sitamarhi",
    "District Court Siwan",
    "District Court Supaul",
    "District Court Vaishali",
    "District Court, Madhubani",
    "District Court, Motihari",
    "District Court, Patna",
    "District Court, Saran at chapra",
    "District Court,Nawada",
    "Khagaria District Court",
    "Kishanganj District Court",
    "Purnea District Court",
    "Sheohar District Court",
    "West Champaran"
  ],
  "Chandigarh": [
    "District Court Chandigarh"
  ],
  "Chhattisgarh": [
    "District and Session Court Kabirdham (Kawardha)",
    "District and Sessions Court Raipur",
    "District and Sessions Court, Durg",
    "District & Sessions Court Bilaspur",
    "District & Sessions Court Dhamtari",
    "District & Sessions Court Korba",
    "District & Sessions Court Raigarh",
    "District and Sessions Court, Kanker",
    "District and Session Court Janjgir-Champa",
    "District and Sessions Court Balodabazar",
    "District and Sessions Court Bastar",
    "District and Sessions Court Bemetara",
    "District and Sessions Court Kondagaon",
    "District and Sessions Court Mahasamund",
    "District and Sessions Court Surajpur",
    "District and Sessions Court Surguja",
    "District and Sessions Court, Balod",
    "District and Sessions Court, Balrampur-Ramanujganj",
    "District and Sessions Court, Jashpur",
    "District and Sessions Court, Korea",
    "District and Sessions Court, Mungeli",
    "District and Sessions Court, Rajnandgaon",
    "District and Sessions Court, South Bastar Dantewada"
  ],
  "Dadra and Nagar Haveli and Daman and Diu": [
    "District & Sessions Court, Dadra and Nagar Haveli at Silvassa",
    "District Court, Daman",
    "District and Sessions Court, Diu"
  ],
  "Delhi": [
    "Central District Court, Delhi",
    "District Court North Delhi",
    "District Court North West Delhi",
    "Dwarka Court, South West Delhi",
    "East District Court, Delhi",
    "New Delhi District Court, Delhi",
    "North East District Court, Delhi",
    "Shahdara District Court, Delhi",
    "South District Court, New Delhi",
    "South-East District Court, New Delhi",
    "West District Court, Delhi"
  ],
  "Goa": [
    "District & Sessions Court, North Goa",
    "District Court South Goa"
  ],
  "Gujarat": [
    "City Civil & Sessions Court Ahmedabad",
    "District Court Ahmedabad Rural",
    "District Court Amreli",
    "District Court Anand",
    "District Court Aravalli",
    "District Court Banaskantha",
    "District Court Bharuch",
    "District Court Bhavnagar",
    "District Court Bhuj Kachchh",
    "District Court Botad",
    "District Court Chhotaudepur",
    "District Court Dahod",
    "District Court Devbhumi Dwarka",
    "District Court Gandhinagar",
    "District Court Gir Somnath",
    "District Court Jamnagar",
    "District Court Junagadh",
    "District Court Kheda",
    "District Court Mahesana",
    "District Court Mahisagar at Lunawada",
    "District Court Morbi",
    "District Court Narmada",
    "District Court Navsari",
    "District Court Panchmahals",
    "District Court Patan",
    "District Court Porbandar",
    "District Court Rajkot",
    "District Court Sabarkantha",
    "District Court Surat",
    "District Court Surendranagar",
    "District Court Tapi",
    "District Court Vadodara",
    "District Court Valsad",
    "Industrial and Labour Courts Ahmedabad",
    "Metropolitan Magistrates Courts, Ahmedabad"
  ],
  "Haryana": [
    "District Court Narnaul",
    "District Court Ambala",
    "District Court Bhiwani",
    "District Court Faridabad",
    "District Court Gurugram",
    "District Court Jhajjar",
    "District Court Jind",
    "District Court Karnal",
    "District Court Kurukshetra",
    "District Court Rohtak",
    "District Court Yamuna Nagar",
    "District Court, Fatehabad",
    "District Court, Hisar",
    "District Court, Kaithal",
    "District Court, Nuh",
    "District Court, Palwal",
    "District Court, Panchkula",
    "District Court, Panipat",
    "District Court, Rewari",
    "District Court, Sirsa",
    "District Court, Sonepat"
  ],
  "Himachal Pradesh": [
    "District Court Bilaspur",
    "District Court Chamba",
    "District Court Hamirpur",
    "District Court Kangra",
    "District Court Kinnaur",
    "District Court Kullu",
    "District Court Mandi",
    "District Court Shimla",
    "District Court Sirmaur",
    "District Court Solan",
    "District Court Una"
  ],
  "Jammu and Kashmir": [
    "District Court Bandipora",
    "District Court Bhaderwah (Doda)",
    "District Court Ganderbal",
    "District Court Pulwama",
    "District Court Rajouri",
    "District Court Anantnag",
    "District Court Baramulla",
    "District Court Budgam",
    "District Court Jammu",
    "District Court Kathua",
    "District Court Kishtwar",
    "District Court Kulgam",
    "District Court Kupwara",
    "District Court Poonch",
    "District Court Ramban",
    "District Court Samba",
    "District Court Shopian",
    "District Court Srinagar",
    "District Court Udhampur",
    "District and Sessions Court, Reasi"
  ],
  "Jharkhand": [
    "Civil Court Hazaribag",
    "Civil Court Khunti",
    "Civil Court Ranchi",
    "Civil Court, Garhwa",
    "Civil Court, Godda",
    "Civil Court, Latehar",
    "Civil Court, Lohardaga",
    "Civil Courts, Dhanbad",
    "Civil Courts Palamau at Daltonganj",
    "Civil Courts, Ramgarh",
    "Civil Court Sahibganj",
    "Civil Court Jamtara",
    "Civil Court Simdega",
    "Civil Court, Chaibasa",
    "Civil Court, Deoghar",
    "Civil Court, Dumka",
    "Civil Court, Giridih",
    "Civil Court, Gumla",
    "Civil Court, Jamshedpur",
    "Civil Court, Koderma",
    "Civil Court, Pakur",
    "Civil Court, Seraikella",
    "Civil Courts, Bokaro",
    "District Court Chatra"
  ],
  "Karnataka": [
    "Bengaluru Urban Courts",
    "District Court Bengaluru Rural",
    "District Court Chamarajanagara",
    "District Court, Kodagu",
    "District Court Ballari",
    "District Court Belagavi",
    "District Court Bidar",
    "District Court Chitradurga",
    "District Court Dakshina Kannada, Mangaluru",
    "District Court Dharwad",
    "District Court Gadag",
    "District Court Hassan",
    "District Court Haveri",
    "District Court Kolar",
    "District Court Koppal",
    "District Court Mysuru",
    "District Court Raichur",
    "District Court Ramanagara",
    "District Court Shivamogga",
    "District Court Tumakuru",
    "District Court Udupi",
    "District Court Uttara Kannada",
    "District Court Vijayapura",
    "District Court Yadgir",
    "District Court, Chikkaballapura",
    "District Court, Chikkamagaluru",
    "District Court, Davanagere",
    "District Court, Kalaburgi",
    "District Court, Mandya",
    "Principal District and Sessions Court Bagalkot"
  ],
  "Kerala": [
    "District & Sessions Court, Pathanamthitta",
    "District Court Kasaragod",
    "District Court Thiruvananthapuram",
    "District Court Alappuzha",
    "District Court Kollam",
    "District Court Kozhikode",
    "District Court Manjeri",
    "District Court Palakkad",
    "District Court Thalassery",
    "District Court Thodupuzha",
    "District Court Thrissur",
    "District Court, Ernakulam",
    "District Court, Kottayam",
    "District and Sessions Court Wayanad"
  ],
  "Ladakh": [
    "District Court Kargil",
    "District Court Leh"
  ],
  "Lakshadweep": [
    "District Court Kavaratti"
  ],
  "Madhya Pradesh": [
    "District & Sessions Court Katni",
    "District & Sessions Court, Rajgarh",
    "District & Session Court Harda",
    "District & Session Court Jabalpur",
    "District & Session Court Shivpuri",
    "District & Session Court, Chhatarpur",
    "District & Session Court, Mandsaur",
    "District & Session's Court Indore",
    "District & Sessions Court Alirajpur",
    "District & Sessions Court Dewas",
    "District & Sessions Court Gwalior",
    "District & Sessions Court Sagar",
    "District & Sessions Court Sheopur",
    "District & Sessions Court Umaria",
    "District & Sessions Court, Ashoknagar",
    "District & Sessions Court, Bhopal",
    "District & Sessions Court, Damoh",
    "District & Sessions Court, Guna",
    "District & Sessions Court, Mandleshwar",
    "District & Sessions Court, Morena",
    "District & Sessions Court, Ratlam",
    "District and Session Court Agar Malwa",
    "District and Session Court Raisen",
    "District and Session Court, Sidhi",
    "District and Sessions Court Satna",
    "District and Sessions Court Singrauli",
    "District and Sessions Court Vidisha",
    "District and Sessions Court, Narsinghpur",
    "District Court Dhar",
    "District Court Shahdol",
    "District Court Tikamgarh",
    "District Court Ujjain",
    "District and Court Sessions Court Jhabua",
    "District and Session Court, Rewa",
    "District and Session Court Anuppur",
    "District and Session Court Bhind",
    "District and Session Court Datia",
    "District and Session Court Shajapur",
    "District and Session Court, Burhanpur",
    "District and Session Court, Narmadapuram",
    "District and Sessions Court, Chhindwara",
    "District and Sessions Court Balaghat",
    "District and Sessions Court Barwani",
    "District and Sessions Court Dindori",
    "District and Sessions Court Khandwa",
    "District and Sessions Court Neemuch",
    "District and Sessions Court Panna",
    "District and Sessions Court Sehore",
    "Principal District & Sessions Court Betul",
    "Principal District and Sessions Court Mandla",
    "Principal District and Sessions Court Seoni"
  ],
  "Maharashtra": [
    "Chief Metropolitan Magistrate Court's, Mumbai",
    "City Civil & Sessions Court, Mumbai",
    "Court of Small Causes, Mumbai",
    "District and Sessions Court Latur",
    "District Court Beed",
    "District & Session Court Pune",
    "District & Sessions Court, Jalna",
    "District & Sessions Court, Nanded",
    "District & Sessions Court, Yavatmal",
    "District Court Amravati",
    "District Court Nagpur",
    "District Court Parbhani",
    "District Court Ratnagiri",
    "District Court, Bhandara",
    "District Court, Chandrapur",
    "District Court, Gadchiroli",
    "District Court, Gondia",
    "District Court, Osmanabad",
    "District Court, Raigad-Alibag",
    "District Court, Solapur",
    "District Court, Wardha",
    "District and Sessions Court Aurangabad",
    "District and Sessions Court Dhule",
    "District and Sessions Court Kolhapur",
    "District and Sessions Court Nandurbar",
    "District and Sessions Court Sindhudurg",
    "District and Sessions Court Thane",
    "District and Sessions Court, Ahmednagar",
    "District and Sessions Court, Akola",
    "District and Sessions Court, Buldana",
    "District and Sessions Court, Jalgaon",
    "District and Sessions Court, Sangli",
    "District and Sessions Court, Satara",
    "District and Sessions Court, Washim",
    "Maharashtra Cooperative Courts",
    "Maharashtra Family Courts",
    "Maharashtra Industrial and Labour Courts",
    "Motor Accident Claims Tribunal, Mumbai",
    "Nashik District Court"
  ],
  "Manipur": [
    "District & Sessions Court, Bishnupur",
    "District & Sessions Court, Imphal West",
    "District and Sessions Court, Churachandpur",
    "District and Sessions Court, Imphal East",
    "District and Sessions Court, Senapati",
    "District and Sessions Court, Tamenglong",
    "District and Sessions Court, Ukhrul",
    "District and Sessions Court, Thoubal"
  ],
  "Meghalaya": [
    "District and Sessions Court, West Jaintia Hills, Khliehtyrshi",
    "District & Sessions Court Khliehriat, East Jaintia Hills",
    "District & Sessions Court, Ampati",
    "District Court Tura",
    "District Court, Resubelpara",
    "District and Sessions Court, Ri Bhoi District, Nongpoh",
    "District and Sessions Court, West Khasi Hills, Nongstoin",
    "East Khasi Hills District Court",
    "South Garo Hills District Court",
    "South West Khasi Hills District Court",
    "Williamnagar District Court"
  ],
  "Mizoram": [
    "District Court, Champhai",
    "District Court, Kolasib",
    "District Court, Lawngtlai",
    "District Court, Lunglei",
    "District Court, Mamit",
    "District Court, Serchhip",
    "District Court, Siaha"
  ],
  "Nagaland": [
    "Dimapur District Court",
    "District Court, Aizawl",
    "Kiphire District Court",
    "Kohima District Court",
    "Longleng District Court",
    "Mokokchung District Court",
    "Mon District Court",
    "Peren District Court",
    "Phek District Court",
    "Tuensang District Court",
    "Wokha District Court",
    "Zunheboto District Court"
  ],
  "Odisha": [
    "Balangir District Court",
    "Court of District & Sessions Judge, Sundargarh",
    "Dhenkanal District Court",
    "District & Sessions Court Bargarh",
    "District & Sessions Court, Malkangiri",
    "District & Sessions Judge Court, Bhadrak",
    "District & Sessions Judge Court, Gajapati at Paralakhemundi",
    "District & Sessions Judge Court, Puri",
    "District Civil & Sessions Court, Balasore",
    "District Court, Kendujhar",
    "District Court Jajpur",
    "District Court Kalahandi",
    "District Court Khurda at Bhubaneswar",
    "District Court Nabarangpur",
    "District Court Nuapada",
    "District Court Sambalpur",
    "District Court, Angul",
    "District Court, Jagatsinghpur",
    "District Court, Kandhamal",
    "District Court, Kendrapara",
    "District Court, Mayurbhanj",
    "District Court, Nayagarh",
    "District Court, Rayagada",
    "District Court, Sonepur",
    "District Court, Koraput at Jeypore",
    "District and Sessions Judge Court, Boudh",
    "District and Sessions Judge Court, Cuttack",
    "District and Sessions Judge Court, Deogarh",
    "District and Sessions Judge Court, Ganjam at Berhampur",
    "District & Sessions Court, Jharsuguda"
  ],
  "Puducherry": [
    "Karaikal District Court",
    "Mahe District Court",
    "Puducherry District Court",
    "Yanam District Court"
  ],
  "Punjab": [
    "District Court Amritsar",
    "District Court Barnala",
    "District Court Bathinda",
    "District Court Faridkot",
    "District Court Fatehgarh Sahib",
    "District Court Fazilka",
    "District Court Ferozepur",
    "District Court Gurdaspur",
    "District Court Hoshiarpur",
    "District Court Jalandhar",
    "District Court Kapurthala",
    "District Court Ludhiana",
    "District Court Mansa",
    "District Court Moga",
    "District Court Pathankot",
    "District Court Patiala",
    "District Court Rupnagar",
    "District Court SAS Nagar",
    "District Court SBS Nagar",
    "District Court Sangrur",
    "District Court Sri Mukatsar Sahib",
    "District Court Tarn Taran"
  ],
  "Rajasthan": [
    "District & Sessions Court Balotra",
    "District Court Dausa",
    "District & Sessions Court Jhunjhunu",
    "District & Sessions Court Jodhpur District",
    "District & Sessions Court Jodhpur Metropolitan",
    "District & Sessions Court Sirohi",
    "District & Sessions Court, Bundi",
    "District & Sessions Court, Jhalawar",
    "District & Sessions Court, Kota",
    "District & Sessions Court, Udaipur",
    "District and Sessions Court Sawai Madhopur",
    "District Court Ajmer",
    "District Court Alwar",
    "District Court Banswara",
    "District Court Bhilwara",
    "District Court Bikaner",
    "District Court Chittorgarh",
    "District Court Dholpur",
    "District Court Dungarpur",
    "District Court Jalore",
    "District Court Merta",
    "District Court Pali",
    "District Court Rajsamand",
    "District Court Sikar",
    "District Court Tonk",
    "District Court, Baran",
    "District Court, Churu",
    "District Court Jaipur Metropolitan II",
    "District and Sessions Court Jaipur Metropolitan I",
    "District and Sessions Court, Bharatpur",
    "District and Sessions Court, Jaipur District",
    "District and Sessions Court, Pratapgarh",
    "Hanumangarh District Court",
    "Jaisalmer District Court",
    "Karauli District Court",
    "Sri Ganganagar District Court"
  ],
  "Sikkim": [
    "District & Sessions Court, Mangan",
    "District & Sessions Court, Namchi",
    "District Court Complex Gyalshing",
    "District Court Gangtok"
  ],
  "Tamil Nadu": [
    "Ariyalur District Court",
    "Chengalpattu District Court",
    "Chennai City Courts",
    "Coimbatore District Court",
    "Cuddalore District Court",
    "Dharmapuri District Court",
    "Dindigul District Court",
    "Erode District Court",
    "Kallakurichi District Court",
    "Kanchipuram District Court",
    "Kanniyakumari District Court",
    "Karur District Court",
    "Krishnagiri District Court",
    "Madurai District Court",
    "Mayiladuthurai District Court",
    "Nagapattinam District Court",
    "Namakkal District Court",
    "Perambalur District Court",
    "Pudukkottai District Court",
    "Ramanathapuram District Court",
    "Ranipet District Court",
    "Salem District Court",
    "Sivagangai District Court",
    "Tenkasi District Court",
    "Thanjavur District Court",
    "The Nilgiris District Court",
    "Theni District Court",
    "Thoothukudi District Court",
    "Tiruchirappalli District Court",
    "Tirunelveli District Court",
    "Tirupathur District Court",
    "Tiruppur District Court",
    "Tiruvallur District Court",
    "Tiruvannamalai District Court",
    "Tiruvarur District Court",
    "Vellore District Court",
    "Villupuram District Court",
    "Virudhunagar District Court"
  ],
  "Telangana": [
    "CBI Court Hyderabad",
    "City Civil Courts Hyderabad and Secunderabad",
    "City Small Causes Court Hyderabad",
    "District Court Jangaon",
    "District Court Medak",
    "District Court Medchal Malkajgiri",
    "District Court Narayanpet",
    "District Court Siddipet",
    "District Court Vikarabad",
    "District Court, Adilabad",
    "District Court, Jagtial",
    "District Court, Kamareddy",
    "District Court, Kumurambheem Asifabad",
    "District Court, Mancherial",
    "District Court, Nirmal",
    "District Judiciary Bhadradri Kothagudem",
    "District Judiciary Hanumakonda",
    "District Judiciary Mulugu",
    "District Judiciary Ranga Reddy",
    "District Judiciary Warangal",
    "District Judiciary, Khammam",
    "District Judiciary, Nizamabad",
    "Hyderabad Integrated Family Courts",
    "Jogulamba Gadwal District Judiciary",
    "Jayashankar Bhupalapally District Judiciary",
    "Karimnagar District Judiciary",
    "Mahabubabad District Judiciary",
    "Mahabubnagar District Judiciary",
    "Metropolitan Sessions Judge, Hyderabad",
    "Nagarkurnool District Judiciary",
    "Nalgonda District Judiciary",
    "Peddapalli District Judiciary",
    "Rajanna Sircilla District Judiciary",
    "Sangareddy Judicial District",
    "Suryapet District Judiciary",
    "Wanaparthy District Judiciary",
    "Yadadri Bhuvanagiri District Judiciary"
  ],
  "Tripura": [
    "District & Sessions Judge Court, Agartala",
    "District & Sessions Judge Court, Gomati",
    "District & Sessions Judge Court, Unakoti",
    "District and Sessions Judge Court, Dhalai",
    "District and Sessions Judge Court, Khowai",
    "District and Sessions Judge Court, North Tripura",
    "District and Sessions Judge Court, Sepahijala",
    "District and Sessions Judge Court, South Tripura"
  ],
  "Uttar Pradesh": [
    "District and Sessions Court Muzaffarnagar",
    "District and Sessions Court Lucknow",
    "District & Sesion Court Ghazipur",
    "District & Sessions Court Jalaun at Orai",
    "District & Sessions Court Jaunpur",
    "District & Sessions Court, Fatehpur",
    "District & Sessions Court, Hardoi",
    "District & Sessions Court, Sant Kabir Nagar",
    "District and Sessions Court Balrampur",
    "District and Sessions Court Sambhal at Chandausi",
    "District Court Agra",
    "District Court Aligarh",
    "District Court Ambedkar Nagar",
    "District Court Amroha",
    "District Court Auraiya",
    "District Court Ayodhya",
    "District Court Baghpat",
    "District Court Bahraich",
    "District Court Banda",
    "District Court Barabanki",
    "District Court Bareilly",
    "District Court Bhadohi at Gyanpur",
    "District Court Bijnor",
    "District Court Bulandshahr",
    "District Court Chandauli",
    "District Court Etah",
    "District Court Etawah",
    "District Court Farrukhabad",
    "District Court Firozabad",
    "District Court Gautam Budh Nagar",
    "District Court Ghaziabad",
    "District Court Gorakhpur",
    "District Court Hamirpur U.P.",
    "District Court Hathras",
    "District Court Jhansi",
    "District Court Kasganj",
    "District Court Kaushambi",
    "District Court Kushinagar",
    "District Court Maharajganj",
    "District Court Mahoba",
    "District Court Mainpuri",
    "District Court Mathura",
    "District Court Meerut",
    "District Court Raebareli",
    "District Court Saharanpur",
    "District Court Shahjahanpur",
    "District Court Shravasti",
    "District Court Sonbhadra",
    "District Court Unnao",
    "District Court Varanasi",
    "District Court, Moradabad",
    "District Court, Prayagraj",
    "District Court, Siddharthnagar",
    "District and Session Court Lakhimpur-Kheri",
    "District and Session Court, Pratapgarh",
    "District and Sessions Court Azamgarh",
    "District and Sessions Court Ballia",
    "District and Sessions Court Basti",
    "District and Sessions Court Budaun",
    "District and Sessions Court Chitrakoot",
    "District and Sessions Court Deoria",
    "District and Sessions Court Gonda",
    "District and Sessions Court Hapur",
    "District and Sessions Court Kannauj",
    "District and Sessions Court Kanpur Dehat",
    "District and Sessions Court Kanpur Nagar",
    "District and Sessions Court Lalitpur",
    "District and Sessions Court Mirzapur",
    "District and Sessions Court Pilibhit",
    "District and Sessions Court Rampur",
    "District and Sessions Court Shamli",
    "District and Sessions Court Sitapur",
    "District and Sessions Court Sultanpur",
    "District and Sessions Court, Mau"
  ],
  "Uttarakhand": [
    "District & Sessions Court Pauri Garhwal",
    "District & Sessions Court Rudraprayag",
    "District & Sessions Court, Chamoli",
    "District and Sessions Court Haridwar",
    "District Court Almora",
    "District Court Champawat",
    "District Court Dehradun",
    "District Court Nainital",
    "District Court Pithoragarh",
    "District Court Tehri Garhwal",
    "District Court Udham Singh Nagar",
    "District Court Uttarkashi",
    "District Court, Bageshwar"
  ],
  "West Bengal": [
    "Alipurduar District Court",
    "Bankura District Court",
    "City Civil Court, Calcutta",
    "City Sessions Court, Calcutta",
    "Darjeeling District and Sessions Judge Court",
    "District Court Hooghly",
    "District Court Dakshin Dinajpur",
    "District Court Howrah",
    "District Court Kalimpong",
    "District Court Murshidabad",
    "District Court North 24 Parganas",
    "District Court Paschim Bardhaman",
    "District Court Purulia",
    "District Court of Purba Bardhaman",
    "District Court, Cooch Behar",
    "District Court, Jhargram",
    "District Court, Malda",
    "District Court, Nadia",
    "District Court, South 24 Parganas",
    "District Judgeship of Birbhum",
    "Jalpaiguri District Court",
    "Paschim Medinipur District Court",
    "Presidency Small Cause Court",
    "Purba Medinipur District Court",
    "Uttar Dinajpur District Court"
  ]
};

export interface TribunalInfo {
  name: string;
  handles: string;
  benchLocations: string;
}

export interface SpecialCourtInfo {
  name: string;
  purpose: string;
  governingLaw: string;
}

export const tribunalsData: TribunalInfo[] = [
  {
    name: "National Company Law Tribunal (NCLT)",
    handles: "Corporate law, insolvency (IBC), company winding-up, oppression & mismanagement",
    benchLocations: "13 benches incl. New Delhi (Principal), Mumbai, Chennai, Kolkata, Ahmedabad, Bengaluru, Hyderabad, Chandigarh, Allahabad, Guwahati, Cuttack, Jaipur, Kochi, Amaravati, Indore"
  },
  {
    name: "National Company Law Appellate Tribunal (NCLAT)",
    handles: "Appeals from NCLT and Competition Commission of India",
    benchLocations: "New Delhi (Principal), Chennai"
  },
  {
    name: "Central Administrative Tribunal (CAT)",
    handles: "Service matters of central government employees",
    benchLocations: "Principal Bench Delhi + ~17 benches across states"
  },
  {
    name: "Income Tax Appellate Tribunal (ITAT)",
    handles: "Appeals in direct tax (income tax) disputes",
    benchLocations: "Benches in ~27 cities nationwide"
  },
  {
    name: "Customs, Excise & Service Tax Appellate Tribunal (CESTAT)",
    handles: "Indirect tax appeals (customs, excise, service tax/GST legacy matters)",
    benchLocations: "Delhi (Principal), Mumbai, Kolkata, Chennai, Bengaluru, Ahmedabad, Hyderabad"
  },
  {
    name: "National Green Tribunal (NGT)",
    handles: "Environmental protection, pollution, forest & wildlife matters",
    benchLocations: "Principal Bench Delhi + Bhopal, Pune, Kolkata, Chennai"
  },
  {
    name: "Debts Recovery Tribunal (DRT) / DRAT",
    handles: "Recovery of bank & financial institution debts",
    benchLocations: "~39 DRT benches; DRAT (appellate) in select cities"
  },
  {
    name: "Securities Appellate Tribunal (SAT)",
    handles: "Appeals against SEBI, PFRDA, IRDAI orders",
    benchLocations: "Mumbai"
  },
  {
    name: "Telecom Disputes Settlement & Appellate Tribunal (TDSAT)",
    handles: "Telecom, broadcasting & spectrum disputes",
    benchLocations: "New Delhi"
  },
  {
    name: "Armed Forces Tribunal (AFT)",
    handles: "Service matters & court-martial appeals of armed forces personnel",
    benchLocations: "Principal Bench Delhi + regional benches"
  },
  {
    name: "Appellate Tribunal for Electricity (APTEL)",
    handles: "Appeals from Central/State Electricity Regulatory Commissions",
    benchLocations: "New Delhi"
  },
  {
    name: "Central Government Industrial Tribunal (CGIT)",
    handles: "Industrial/labour disputes involving central government undertakings",
    benchLocations: "Multiple cities (Mumbai, Kolkata, Chennai, Kanpur, etc.)"
  },
  {
    name: "National Consumer Disputes Redressal Commission (NCDRC)",
    handles: "Apex consumer forum; also State & District Consumer Commissions",
    benchLocations: "New Delhi (national); State & District commissions in every state/district"
  },
  {
    name: "Real Estate Regulatory Authority (RERA) / Appellate Tribunal",
    handles: "Real estate project & builder-buyer disputes",
    benchLocations: "One RERA authority per state/UT"
  },
  {
    name: "Competition Commission of India (CCI)",
    handles: "Anti-competitive practices, market regulation (appeals go to NCLAT)",
    benchLocations: "New Delhi"
  }
];

export const specialCourtsData: SpecialCourtInfo[] = [
  {
    name: "Family Courts",
    purpose: "Matrimonial disputes, divorce, maintenance, child custody & guardianship",
    governingLaw: "Family Courts Act, 1984"
  },
  {
    name: "Fast Track Courts / Fast Track Special Courts (FTSC)",
    purpose: "Speedy trial of rape/POCSO and other heinous crime cases",
    governingLaw: "State-level scheme"
  },
  {
    name: "POCSO Courts",
    purpose: "Offences under the Protection of Children from Sexual Offences Act",
    governingLaw: "POCSO Act, 2012"
  },
  {
    name: "CBI Courts (Special Courts)",
    purpose: "Cases investigated by the Central Bureau of Investigation",
    governingLaw: "Delhi Special Police Establishment Act, 1946"
  },
  {
    name: "NIA Special Courts",
    purpose: "Terrorism and offences investigated by the National Investigation Agency",
    governingLaw: "NIA Act, 2008"
  },
  {
    name: "Special Courts for MPs/MLAs",
    purpose: "Criminal cases against sitting/former legislators",
    governingLaw: "Supreme Court directions"
  },
  {
    name: "Anti-Corruption / Vigilance Courts",
    purpose: "Prevention of Corruption Act cases against public servants",
    governingLaw: "Prevention of Corruption Act, 1988"
  },
  {
    name: "NDPS Special Courts",
    purpose: "Narcotic drugs and psychotropic substances offences",
    governingLaw: "NDPS Act, 1985"
  },
  {
    name: "Prevention of Money Laundering Act (PMLA) Special Courts",
    purpose: "Money-laundering offences (ED prosecutions)",
    governingLaw: "PMLA, 2002"
  },
  {
    name: "Commercial Courts",
    purpose: "High-value commercial disputes (₹3 lakh+ specified value)",
    governingLaw: "Commercial Courts Act, 2015"
  },
  {
    name: "Labour Courts / Industrial Tribunals (State)",
    purpose: "Industrial and labour disputes at state level",
    governingLaw: "Industrial Disputes Act, 1947"
  },
  {
    name: "Motor Accidents Claims Tribunal (MACT)",
    purpose: "Compensation claims arising from motor vehicle accidents",
    governingLaw: "Motor Vehicles Act, 1988"
  },
  {
    name: "Juvenile Justice Boards",
    purpose: "Cases involving children in conflict with law",
    governingLaw: "Juvenile Justice Act, 2015"
  },
  {
    name: "Lok Adalats / Gram Nyayalayas",
    purpose: "Alternative dispute resolution, village-level access to justice",
    governingLaw: "Legal Services Authorities Act, 1987 / Gram Nyayalayas Act, 2008"
  }
];



